import Carousel from '../../components/Carousel';
import Vines from '../../assets/Portfolio/Vines/VinesHighlights.gif';
import VinesSplash from '../../assets/Portfolio/Vines/VinesSplash.jpg';
import QuasarEscape from '../../assets/Portfolio/QuasarEscape/QuasarEscape.gif';
import AxisLost from '../../assets/Portfolio/AxisLost/AxisLost.gif';
import oneButtonAssortment from '../../assets/Portfolio/OneButton/OneButtWide.gif';
import LaForret from '../../assets/Portfolio/LaFor/LaForWide.png';
import CurseMon from '../../assets/Portfolio/CursMon/CurseMonBlank.png'
import toyBox from '../../assets/Portfolio/toyboxCombined.gif'
import Grimwood from '../../assets/Portfolio/Grimwood/grimwood.gif'
import ferrous from '../../assets/Portfolio/ferrous/FerrousHawk.gif'

function Portfolio() {
  const items = [
    {
      title: 'Vines',
      subtitle: 'A foray into procedural generation, inventory management, and UI design.',
      to: '/Portfolio/Vines',
      image: Vines,
      previewImage: VinesSplash,
    },
    {
      title: 'Quasar Escape',
      subtitle: 'Implemented compelling movement, and randomized planets.',
      to: '/Chocolate',
      image: QuasarEscape,
      previewImage: QuasarEscape,
    },
    {
      title: 'Axis Lost',
      subtitle: 'My job was (spoiler) implementing portals for the seamless warping of space.',
      to: '/Engineer',
      image: AxisLost,
      previewImage: AxisLost,
    },
    {
      title: 'One Button Assortment',
      subtitle: 'A series of games made in crisp-game-lib that explore the boundaries of a single button interaction.',
      to: '/Engineer',
      image: oneButtonAssortment,
      previewImage: oneButtonAssortment,
    },
    {
      title: 'La Forret',
      subtitle: 'A storytelling and prototyping exercise focused on overlaying narrative space and physical space.',
      to: '/Engineer',
      image: LaForret,
      previewImage: LaForret,
    },
    {
      title: 'Curse That Pokemon!',
      subtitle: 'A rush job reskinning of an image generation ai.',
      to: '/Portfolio',
      image: CurseMon,
      previewImg: CurseMon,
    },
    {
      title: 'ToyBox',
      subtitle: 'A combo of various unity experiments that don\'t qualify as full games. Space game is based around making satisfying jump and stick movement, and toy box is just tests for any unity system that caught my eye.',
      to: '/Portfolio',
      image: toyBox,
      previewImg: toyBox,
    },
    {
      title: 'Grimwood Path',
      subtitle: 'I became the link between our sprite artist and what appeared on the screen. My focus was using the assets generated by the artist to tell the story of the game.',
      to: '/Portfolio',
      image: Grimwood,
      previewImg: Grimwood,
    },
    {
      title: 'Ferrous Hawk',
      subtitle: 'My focus was on creating communication prototypes and implementing the quick time event portion of the final game.',
      to: '/Portfolio',
      image: ferrous,
      previewImg: ferrous,
    }
  ];

  return (
    <>
      <section id="content">
        <h1>A selection of games</h1>
        <Carousel items={items} />
        <div>
          direct and boring links... (TODO)
        </div>

      </section>
    </>
  );
}

export default Portfolio;