import * as React from 'react';
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import Box from '@mui/material/Box';




//import pictures
// import Beacon from '../../assets/Portfolio/Vines/Beacon.gif'
// import CamVines from '../../assets/Portfolio/Vines/CamVines.gif'
// import Chirper from '../../assets/Portfolio/Vines/ChirperDeply.gif'
// import CubeVines from '../../assets/Portfolio/Vines/CubeVines.gif'
// import HUD from '../../assets/Portfolio/Vines/HUDdemo.gif'
// import ItemWheelCropped from '../../assets/Portfolio/Vines/ItemWheelCropped.gif'
// import ItemWheelWide from '../../assets/Portfolio/Vines/ItemWheelWide.gif'
// import ItemWheelAndMenu from '../../assets/Portfolio/Vines/MenuAndItemWheelCombined.gif'
// import Menu from '../../assets/Portfolio/Vines/MenuExample.gif'
// import Outlines from '../../assets/Portfolio/Vines/OutlineComparisions.png'
// import Scanner from '../../assets/Portfolio/Vines/ScannerSweap.gif'
// import SeekerVines from '../../assets/Portfolio/Vines/SeekerVinesDemo.gif'
// import SmartVines from '../../assets/Portfolio/Vines/SmartVinesHighlighted.gif'
// import StaticVines from '../../assets/Portfolio/Vines/StaticVineCombo.gif'
// import HighlightReel from '../../assets/Portfolio/Vines/VinesHighlights.gif'
// import VinesSplash from '../../assets/Portfolio/Vines/VinesSplash.jpg'
// import VinnyWithVines from '../../assets/Portfolio/Vines/VinnyWithRaycastVines.gif'
// import VineWriggle from '../../assets/Portfolio/Vines/WriggleCloseUp.gif'


interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number;
}

function CustomTabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && <Box sx={{ p: 3 }}>{children}</Box>}
    </div>
  );
}

function a11yProps(index: number) {
  return {
    id: `simple-tab-${index}`,
    'aria-controls': `simple-tabpanel-${index}`,
  };
}



function Vines() {
  const [value, setValue] = React.useState(0);

  const handleChange = (_event: React.SyntheticEvent, newValue: number) => {
    setValue(newValue);
  };

  return (
    <>
     <Box sx={{ width: '100%' }}>
        <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
            <Tabs 
                value={value} 
                onChange={handleChange} 
                textColor="secondary" 
                indicatorColor='secondary'
                aria-label="VinesTabs" 
            >
                <Tab label="Overview" {...a11yProps(0)} />
                <Tab label="Procedural Vines" {...a11yProps(1)} />
                <Tab label="Items" {...a11yProps(2)} />
                <Tab label="UI Work" {...a11yProps(3)} />
            </Tabs>
        </Box>
            <CustomTabPanel value={value} index={0}> {/*overview*/}
                <ul>
                    <li><span>Vines</span><br></br>I created a variety of procedurally generated vines to fill various aesthetic and gameplay needs.</li>
                    <li><span>Items</span><br></br>I inherited the Item code and extended it to add a few new items and capabilities.</li>
                    <li><span>UI</span><br></br>Taking on a more technical artist role, I animated, rigged, and styled the in-game menu and UI.</li>
                    <div className="social-icons">
                        <a href="https://github.com/TPlemur/Vines"><i className="fa-brands fa-github"></i></a>
                        <a href="https://es-jacque.itch.io/vines"><i className="fa-brands fa-itch-io"></i></a>
                    </div>

                    <div className="tab-img active-img" id="overviewimg">
                        <img src="../Assets/GameImages/VinesImg/VinesHighlits.gif"></img>
                    </div>

                </ul>
            </CustomTabPanel>
            <CustomTabPanel value={value} index={1}> {/*vines*/}
                <ul>
                    <li><span>What do vines need to do?</span><br></br>Our design required vines that could grow and wither across a procedurally generated map. I quickly made a shader that used alpha clipping and offset to animate the vines, 
                        but finding surfaces was more difficult. I tried several approaches.</li>
                    <li><span>Cloth?</span><br></br>The easiest solution - Make a bunch of vine shaped objects and use Unity's cloth physics to provide a semblance of life. Easy to implement, but with lackluster results.</li>
                    <li><span>Raycasting?</span><br></br>A solution initially provided by the internet. I heavily adapted the code I was following to make it much more modular, allowing a variety of vine characteristics to be generated by one script. 
                        I also had to custom re-make the shader, as the original shader was incompatible with URP. This creates beautiful vines, but with a hefty performance cost.</li>
                    <li><span>Marching Cubes?</span><br></br>An original concept, made as a response to the performance issues in the raycast vines. The algorithm generates a cubic graph and then eliminates first any point contained within a terrain collider, 
                        then any point still connected in all directions. Vines are then generated by traversing the remaining graph. It's highly efficient, but the vines are very angular.</li>
                    <li><span>Crawler Vines</span><br></br>This is the current solution. I reworked the original raycasting solution to generate vines one node at a time, instead of all at once. This improves performance, 
                        and allows the vines to wander around the map like snakes. This also allows the generation load to be spread across more ticks, reducing overall performance spike issues.</li>
                    <li><span>Smart Vines</span><br></br>By layering a state machine on top of the Crawler Vines they are granted a semblance of intelligence. These vines can seek out the player, detect their presence, and report back to the monster.</li>
                    <div className="social-icons">
                        <a href="https://github.com/TPlemur/Vines"><i className="fa-brands fa-github"></i></a>
                        <a href="https://es-jacque.itch.io/vines"><i className="fa-brands fa-itch-io"></i></a>
                    </div>
                </ul>
                <div className="work-list2">
                    <div className="work">
                        <img src="../Assets/GameImages/VinesImg/StaticVineCombo.gif"></img>
                        <div className="layer">
                            <h3>Static Vines</h3>
                            <p>The most basic strategy, using Unity's cloth. Creates somewhat lackluster vines that hang limply and are mostly suitable for draping across the facility.</p>
                        </div>
                    </div>
                    <div className="work">
                        <img src="../Assets/GameImages/VinesImg/VinnyWithRaycastVines.gif"></img>
                        <div className="layer">
                            <h3>Raycasting</h3>
                            <p>Each vine raycasts in a sweep to find the next point on the surface. This technique is excellent at following any surface, but suffers from performance issues with many vines.</p>
                        </div>
                    </div>
                    <div className="work">
                        <img src="../Assets/GameImages/VinesImg/CubeVines.gif"></img>
                        <div className="layer">
                            <h3>Marching Cubes</h3>
                            <p>This method front loads the surface finding, using an algorithm inspired by marching cubes to eliminate points from a matrix leaving only the surface of the map. Vines are highly efficient, but tend to be angular.</p>
                        </div>
                    </div>
                    <div className="work">
                        <img src="../Assets/GameImages/VinesImg/SmartVinesHighlighted.gif"></img>
                        <div className="layer">
                            <h3>Crawlers</h3>
                            <p>Combines the appealing aesthetic of the raycast vines with a more performance friendly generation pattern. Each new node is only generated as needed, and the vines are spawned with a tick offset to spread the load out.</p>
                        </div>
                    </div>
                </div>

                <div className="process" id="processShowHide">
                    
                    <h1 className="sub-title">Assorted Extra Vines</h1>
                    <div className="work-list">
                        <div className="work">
                            <img src="../Assets/GameImages/VinesImg/SeekerVinesDemo.gif"></img>
                            <div className="layer">
                                <h3>Seeker Vines</h3>
                                <p>Raycast based vines that spawn near and seek out the player, used to enforce player movement.</p>
                            </div>
                        </div>
                        <div className="work">
                            <img src="../Assets/GameImages/VinesImg/VinesGrownOnVinny.png"></img>
                            <div className="layer">
                                <h3>Growing Vines on Splitjaw</h3>
                                <p>We couldn't get procedurally generated vines to attach themselves to the splitjaw's rig at runtime. Instead I generated some vines on his mesh and sent them to our modeler to attach.</p>
                            </div>
                        </div>
                        <div className="work">
                            <img src="../Assets/GameImages/VinesImg/CamVines.gif"></img>
                            <div className="layer">
                                <h3>Camera Vines</h3>
                                <p>Growing vines on the camera before it gets disconnected.</p>
                            </div>
                        </div>
                        <div className="work">
                            <img src="../Assets/GameImages/VinesImg/WriggleCloseUp.gif"></img>
                            <div className="layer">
                                <h3>Wriggling</h3>
                                <p>I added some wriggle to the vine shader, making them feel much more alive.</p>
                            </div>
                        </div>
                    </div>
                </div>

            </CustomTabPanel>
            <CustomTabPanel value={value} index={2}> {/*items*/}
                <ul>
                    <li><span>Technical Debt</span><br></br>I inherited the item code from another team member when they moved on from the project. Before I could work on creating new items I first had to learn how the existing code works, 
                        and I cleaned up a few warnings related to instantiation.</li>
                    <li><span>Scanner</span><br></br>We found that players felt a lack of direction while playing. While the players were given an orientation at the beginning of the game, they still felt lost. So how do you give the player hints about where to go, 
                        without trivializing the maze aspect of the game? My solution was to give approximate distance and direction to places of interest, but not reveal what the location was.</li>
                    <li><span>Shield</span><br></br>To highlight the scariness of the monster we wanted to allow the player a non-fatal encounter with it, but struggled with how to avoid undermining the perceived lethality. 
                        I came up with a single use deployable shield as the solution.</li>
                    <li><span>Beacon</span><br></br>Building on the success of the scanner, this lets the player create a scanner location. </li>
                    <li><span>Chirper</span><br></br>The final task of the game is to get a picture of the monster using the CCTV cameras in fixed locations about the map. However, the players had a very difficult time luring the monster past one without getting killed. 
                        This attempts to combat this by giving a low priority investigation target for the monster.</li>
                    <div className="social-icons">
                        <a href="https://github.com/TPlemur/Vines"><i className="fa-brands fa-github"></i></a>
                        <a href="https://es-jacque.itch.io/vines"><i className="fa-brands fa-itch-io"></i></a>
                    </div>    
                </ul>

                <div className="tab-img" id="itemsimg">
                    <div className="work-list2">
                        <div className="work">
                            <img src="../Assets/GameImages/VinesImg/ScannerSweap.gif"></img>
                            <div className="layer">
                                <h3>Scanner</h3>
                                <p>Originally a separate item, but reworked as part of the electrical tools</p>
                            </div>
                        </div>
                        <div className="work">
                            <img src="../Assets/GameImages/VinesImg/ShieldDeploying.gif"></img>
                            <div className="layer">
                                <h3>Shield</h3>
                                <p>I made the deployed wall expand to fill the space, blocking off the corridor without clipping into the walls.</p>
                            </div>
                        </div>
                        <div className="work">
                            <img src="../Assets/GameImages/VinesImg/Beacon.gif"></img>
                            <div className="layer">
                                <h3>Beacon</h3>
                                <p>Beep... Beep... Beep... </p>
                            </div>
                        </div>
                        <div className="work">
                            <img src="../Assets/GameImages/VinesImg/ChirperDeply.gif"></img>
                            <div className="layer">
                                <h3>Chirper</h3>
                                <p>Makes noise!</p>
                            </div>
                        </div>
                    </div>
                </div>


            </CustomTabPanel>
            
            <CustomTabPanel value={value} index={3}> {/* UI */}
                <ul>
                    <li><span>Outlines</span><br></br>Players were struggling to find interactables, so as a temporary solution I made a script to change the material of the object when the player looks at it. 
                        By changing it to a secondary material with a custom shader it became its final form as the outline seen in the game.</li>
                    <li><span>Pause Menu</span><br></br>One of the most difficult aspects of the pause menu was making it function as a prefab, despite its need to reference various external scripts and gameobjects.</li>
                    <li><span>Item Wheel</span><br></br>I created both the sprite and code for this, and players have the option to either specifically select any item, or to rotate through them.</li>
                    <li><span>HUD</span><br></br>I styled and animated the existing UI elements, and added some new ones. </li>
                    <div className="social-icons">
                        <a href="https://github.com/TPlemur/Vines"><i className="fa-brands fa-github"></i></a>
                        <a href="https://es-jacque.itch.io/vines"><i className="fa-brands fa-itch-io"></i></a>
                    </div>    
                </ul>

                <div className="work-list2">
                    <div className="work">
                        <img src="../Assets/GameImages/VinesImg/OutlineComparisions.png"></img>
                        <div className="layer">
                            <h3>Outlines</h3>
                            <p>A more aesthetic replacement for making the entire item change to a solid color.</p>
                        </div>
                    </div>
                    <div className="work">
                        <img src="../Assets/GameImages/VinesImg/MenuExample.gif"></img>
                        <div className="layer">
                            <h3>Pause Menu</h3>
                            <p>Replaced a very temporary gray box. Not my design, by my implementation</p>
                        </div>
                    </div>
                    <div className="work">
                        <img src="../Assets/GameImages/VinesImg/ItemWheel16_9.gif"></img>
                        <div className="layer">
                            <h3>Item Wheel</h3>
                            <p>Allows the player to track what they have, and choose each item.</p>
                        </div>
                    </div>
                    <div className="work">
                        <img src="../Assets/GameImages/VinesImg/HUDdemo.gif"></img>
                        <div className="layer">
                            <h3>HUD</h3>
                            <p>Little animations and fixing to have consistent styling</p>
                        </div>
                    </div>
                </div>
            </CustomTabPanel>
        </Box>

      
    </>
  )
}

export default Vines